version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: dbuser
      DB_PASSWORD: dbpassword
      DB_NAME: mydatabase

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
